export enum ACCOUNT_ROLE {
    ADMIN = 'ADMIN',
    USER = 'USER'
}


export enum ACCOUNT_STATUS {
    APPROVAL_PENDING = "APPROVAL_PENDING",
    ACTIVE = "ACTIVE",
    INACTIVE = "INACTIVE",
    BLOCKED = "BLOCKED",
    DELETED = "DELETED",
}